import localFont from 'next/font/local'
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer"
import { ThemeProvider } from '@mui/material';
import theme from "./utils/theme"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Satoshi = localFont({ src: '../../public/fonts/Satoshi-Medium.ttf' })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
      <body className={Satoshi.className}>
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
      </ThemeProvider>
    </html>
  );
}
